# Terminal & colors (works locally, in Docker, and over SSH)
set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:Tc"
set -g allow-passthrough on
set -s escape-time 0

# Enable activity alerts
set -g monitor-activity on
set -g visual-bell off
set -g visual-activity off
set -g visual-silence off

set -g renumber-windows on # Reorder window numbers

set -g base-index 1
set -g pane-base-index 1

# Add title to the terminal
set -g set-titles on
# WIP Below (I am trying to find a good balance here)
# It shows and emoji in the title when prefix is pressed.
set -g set-titles-string '#{pane_current_command} · #S:#W · #H #{session_alerts} #{?client_prefix,✼,}'

setw -g allow-rename off
setw -g automatic-rename off

# <prefix> r (reload) - Reloads .tmux.conf
bind r run-shell -b '\
  tmux source-file ~/.tmux.conf ; \
  tmux display-message "Config reloaded 🌀..."; \
'
# Popup Keybinds
# <prefix> Ctrl+n (notes) - Opens nvim for notes
# bind-key C-n display-popup -E -w 80% -h 80% "${HOME}/dotfiles/tmux/scripts/make_note.sh"
# <prefix> Ctrl+p (Python REPL) - Opens Python REPL (quit closes)
# bind-key C-p display-popup -E -w 80% -h 80% "${HOME}/.pyenv/shims/python"
# <prefix> Ctrl+h (htop) - Opens htop (q closes)
bind-key C-h display-popup -E -w 80% -h 80% "htop"
# <prefix> Ctrl+t (terminal) - Opens a new terminal popup (exit closes)
bind-key C-t display-popup -E -w80% -h80% ""

# THEME
set -g prompt-cursor-colour white
set -g status-left-style NONE
set -g status-right-style NONE

# Status left
set -g status-left-length 1
set -g status-left ''

# Status right
set -g status-right-length 30
set -g status-right "#{?client_prefix,#[fg=cyan bg=black] #S [#h] ,#[fg=white dim bg=black] #S [#h] }"

# Messages
set -g message-style "fg=cyan,bg=black"
set -g message-command-style "fg=cyan,bg=black"

# Enable status bar
set -g status "on"
set -g status-justify "left"

setw -g window-status-style "NONE,fg=black,bg=cyan"
setw -g window-status-format "#[fg=black,bg=cyan]  #W:#I#F  #[default]"
setw -g window-status-current-format "#[fg=white, bg=black] #W:#I#F #[default]"

# Reset some style if it is configured
setw -g window-status-separator ""
setw -g window-status-activity-style ""

set -g mode-style "fg=white,bg=#3b4fa6"
set -g message-command-style "fg=cyan,bg=black"
set -g message-style "fg=cyan,bg=black"

set -g status-style "fg=black,bg=cyan"


# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible' # Configurações sensatas padrão

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-yank'

# set -g @plugin 'catppuccin/tmux'

set -g @plugin 'sainnhe/tmux-fzf'

# Continuum
set -g @continuum-restore 'on'

# Mouse
set -g mouse on

# Histórico
set -g history-limit 100000

# Recarregar configuração
bind r source-file ~/.tmux.conf \; display-message "Config recarregada"

# Carregar TPM (DEVE SER A ÚLTIMA LINHA)
run '~/.tmux/plugins/tpm/tpm'
